### ISSUE TITLE
Permission to maintain

### ISSUE THREAD

**Issue by cherryblossom2020** [maximatically/vinter-wiki#1]
Hi!

We are interested in forking your project and maintain wiki with newest game informations. I wanted to ask permission if we are allowed to do so. We will give you credit as original author. 

Thank you!

**Comment by xibn** [comment]
> Hi!
> 
> We are interested in forking your project and maintain wiki with newest game informations. I wanted to ask permission if we are allowed to do so. We will give you credit as original author.
> 
> Thank you!

Sure I have no problem with that, I could also add you as a maintainer or help with the work on yours I just abandoned this project since the korean wiki got an english translation. Btw, who is we? Ohh and btw the vinter.wiki domain is not registered anymore.

**Comment by cherryblossom2020** [comment]
I'm Arlo and I'm system engineer from Uuvana Studios. It would be great to work with you on the wiki!. I will fork the repository and invite you if you are interested.

**Comment by xibn** [comment]
> I'm Arlo and I'm system engineer from Uuvana Studios. It would be great to work with you on the wiki!. I will fork the repository and invite you if you are interested.

Ohh very cool, I didn't realize you were from Uuvana Studios. Go ahead I would be happy to help :)
